// {{NAME}} — generated by create-eyeread.in-packs.
//
// Full API reference: https://github.com/omniship-labs/eyeread.in-packs-sdk/blob/main/spec/API.md
// Editor autocomplete: npm install --save-dev @omniship-labs/eyeread.in-packs-types

eyeread.on('{{PERMISSION}}', async (ctx) => {
  const values = await eyeread.settings.get();
  console.log(values.greeting ?? 'Hello from {{NAME}}');
});

// A pack registers one handler per permission it declares in pack.json.
// Examples for the other permissions (add the permission to pack.json first):
//
// eyeread.on('scripts:write', async ({ scripts, net, settings }) => {
//   const { scriptId } = await scripts.add({ title: 'New script', text: 'Hello' });
// });
// eyeread.on('prompter:load', ({ prompter }) => {
//   prompter.load({ text: 'Hello' });
// });
// eyeread.on('prompter:control', async ({ prompter }) => {
//   await prompter.pause();
// });
// eyeread.on('prompter:events', ({ prompter }) => {
//   const stop = prompter.onState((state) => console.log(state));
// });
// eyeread.on('files:import', async ({ files }) => {
//   const file = await files.import({ accept: ['.txt'] });
// });

eyeread.settings.onChange((values) => {
  console.log('settings changed', values);
});
